site_name: Such Meme, Many Skill's Dumping Ground
theme: cinder
markdown_extensions:
  - admonition
nav:
    - Home: index.md
    - Guides:
        - 'Old':
            - 'Switch Theming Guide (external site)': 'https://nh-server.github.io/switch-guide/extras/theming/'
            - 'Switch Nand Restore Guide': 'guides/nandrestore.md'
            - 'Installing AutoRCM': 'guides/autorcm.md'
            - 'Switch Hackable Serial List': 'guides/switchserials.md'
            - 'Emummc manual Guide': 'guides/emunand.md'
            - 'Emummc manual linux Guide': 'guides/emunand_linux.md'
            - 'Old Unbrick Guide': 'guides/unbrick_old.md'
        - 'Switch Dump & Installing Guide': 'guides/switchdumpguide.md'
        - 'SysMMC save extract': 'guides/switchextractsaves.md'
        - 'Switch Unbrick Guide': 'guides/unbrick.md'
        
    - Apps:
        - 'Old':
            - 'Switch Theme Bat Script': 'apps/themebatscript.md'
            - 'CubeAdventure - Game by me': 'apps/CubeAdventure.md'
        - 'Payload Launcher': 'apps/payload.md'
        - 'TegraExplorer': 'apps/TegraExplorer.md'
        - 'EmmcHaccGen': 'apps/emmchaccgen.md'
    - Themes:
        - 'General Theme Sites': 'Themes/General_Theme_Sites.md'
        - 'My 3ds Themes': 'Themes/3ds_Themes.md'
        - 'My Switch Themes': 'Themes/Switch_Themes.md'
    - About: about.md
    
google_analytics:
    - UA-135654881-1
    - auto

extra_css:
    - css/custom.css